In [32]:
from argparse import ArgumentParser
import shutil
import os
from tensorboard.backend.event_processing.event_file_inspector import get_inspection_units, print_dict, get_dict_to_print

In [4]:
inspect_units = get_inspection_units(logdir="/home/jovyan/work/notebooks/runs")

Found event files in:
/home/jovyan/work/notebooks/runs/unet_27_05_2022_171329
/home/jovyan/work/notebooks/runs/unet_01_03_2023_102208
/home/jovyan/work/notebooks/runs/unet_16_11_2022_150534
/home/jovyan/work/notebooks/runs/unet_14_06_2022_092353
/home/jovyan/work/notebooks/runs/unet_06_07_2022_094605
/home/jovyan/work/notebooks/runs/unet_28_02_2023_112147
/home/jovyan/work/notebooks/runs/unet_30_05_2022_085040
/home/jovyan/work/notebooks/runs/unet_08_06_2022_062915
/home/jovyan/work/notebooks/runs/smp_unet_07_03_2023_144840
/home/jovyan/work/notebooks/runs/unet_pretrained_04_07_2022_141315
/home/jovyan/work/notebooks/runs/unet_15_12_2022_111005
/home/jovyan/work/notebooks/runs/unet_17_05_2022_085640
/home/jovyan/work/notebooks/runs/unet_17_05_2022_090358
/home/jovyan/work/notebooks/runs/unet_23_01_2023_143459
/home/jovyan/work/notebooks/runs/unet_09_12_2022_140432
/home/jovyan/work/notebooks/runs/deeplabv3_16_06_2022_090705
/home/jovyan/work/notebooks/runs/unet_02_06_2022_122641
/home/

In [6]:
len(inspect_units)

379

In [ ]:
list(inspect_units[0])[2]["scalars"]

In [29]:
list(run)[0]

'/home/jovyan/work/notebooks/runs/unet_12_11_2022_100351'

In [37]:
# inspect_units = get_inspection_units(logdir="/home/jovyan/work/notebooks/runs")


for run in inspect_units:
    r = list(run)
    filepath = r[0]
    if len(list(r)[2]["scalars"]) == 0:
        if os.path.isdir(filepath):
            shutil.rmtree(filepath)

In [36]:
filepath

'/home/jovyan/work/notebooks/runs/unet_12_11_2022_100351'

In [46]:
import torch

a  = torch.randn(100,12)

In [47]:
a.sum(1).shape

torch.Size([100])

In [45]:
a.shape[-2:].numel()

60

In [ ]:
torch

In [ ]:
torch.tensor([[[1,2,]]])

In [39]:
a.shape

torch.Size([100, 12])

In [24]:
import geopandas as gpd
import numpy as np
df = gpd.read_file("ne_10m_admin_0_countries.shp")

0      False
1      False
2      False
3      False
4      False
       ...  
253    False
254    False
255    False
256    False
257    False
Name: SOVEREIGNT, Length: 258, dtype: bool

SOVEREIGNT                                           geometry
36   South Africa  MULTIPOLYGON (((19.98145 -24.75249, 19.98641 -...
145       Lesotho  POLYGON ((28.98085 -28.90904, 28.99542 -28.908...

In [35]:
gdf = df[["SOVEREIGNT","geometry"]]
gdf = gdf[(gdf["SOVEREIGNT"] == "South Africa") ]
gdf.to_file("borders_sa.geojson")

In [44]:
import rasterio
p = "/home/jovyan/work/satellite_data/tmp/inference/smp_unet_mitb3_08_03_2023_170715.pth/2019/canopy_cover_rasters/canopy_cover_100m_test.tif"

src = rasterio.open(p)
a = src.read(1)

In [45]:
np.unique(a)

array([  0, 100], dtype=uint8)

In [74]:
import torch

# Define the desired shape of the array
desired_shape = torch.tensor((4, 4))

# Create an example array
arr = torch.tensor([3, 4])

arr.shape == desired_shape

if arr.ndim == 1:
    arr = arr.unsqueeze(0)

padded_tensor = torch.zeros(desired_shape, dtype=tensor.dtype)
padded_tensor[:tensor.size(0), :tensor.size(1)] = tensor

NameError: name 'tensor' is not defined

In [82]:
# create a sample tensor
tensor = torch.tensor( [3, 4])

# define the desired shape
desired_shape = np.array([3, 4])

# check if the tensor has two dimensions and the desired shape
if tensor.size() == torch.Size(desired_shape):
    print("The tensor has the desired shape.")
else:
    tensor = tensor.unsqueeze(0)
    # pad the missing parts with zeros
    padded_tensor = torch.zeros(desired_shape.tolist(), dtype=tensor.dtype)
    padded_tensor[:tensor.size(0), :tensor.size(1)] = tensor
    print("The tensor has been padded with zeros to the desired shape.")
    print(padded_tensor)

The tensor has been padded with zeros to the desired shape.
tensor([[3, 4, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [80]:
padded_tensor.shape

torch.Size([3, 4])

In [73]:
arr_padded.shape

torch.Size([1, 7])

In [49]:
arr.shape

(2, 2)

In [102]:
driver = gdal.GetDriverByName('COG')

In [104]:
driver.Create()

TypeError: Driver_Create() missing required argument 'utf8_path' (pos 2)

In [110]:
import numpy as np
from osgeo import gdal, gdal_array
import matplotlib.pyplot as plt

# Open the input raster file
input_file = '/home/jovyan/work/satellite_data/tmp/inference/smp_unet_mitb3_08_03_2023_170715.pth/SA_cover_map.tif'
ds = gdal.Open(input_file)

# Read the input raster data into a numpy array
band = ds.GetRasterBand(1)
data = band.ReadAsArray()

# Apply the viridis colormap to the input data
colormap = gdal.ColorTable()
for i in range(256):
    color = plt.cm.viridis(i/255.0)[:3]
    colormap.SetColorEntry(i, (int(color[0]*255), int(color[1]*255), int(color[2]*255), 255))

# Create a new raster file with the viridis colormap
output_file = 'output.tif'

driver = gdal.GetDriverByName('Gtiff')
out_ds = driver.Create(output_file, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Byte,options=["COMPRESS=LZW","PREDICTOR=2"])
out_ds.SetProjection(ds.GetProjection())
out_ds.SetGeoTransform(ds.GetGeoTransform())
#out_ds.SetCompression(gdal.COMPRESSION_LZW)
out_band = out_ds.GetRasterBand(1)
out_band.SetRasterColorTable(colormap)
out_band.SetNoDataValue(255)
out_band.WriteArray(data)

# Clean up
del ds, band, out_band, out_ds

In [106]:
out_ds.SetNoDataValue()

AttributeError: 'Dataset' object has no attribute 'SetNoDataValue'

In [91]:
driver.Create()

TypeError: Driver_Create() missing required argument 'utf8_path' (pos 2)

In [90]:
data.shape

(14109, 15985)

In [86]:
data

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)